name: Android APK CI

on:
  push:
    branches: ["**"]
    tags: ["v*"]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Install JS dependencies
        run: pnpm install

      - name: Build Lynx bundle
        run: pnpm run build

      - name: Copy Lynx bundle to Android assets
        run: |
          mkdir -p app/src/main/assets
          cp dist/main.lynx.bundle app/src/main/assets/

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build APKs
        run: ./gradlew :app:assembleRelease

      - name: Sign APK
        uses: ilharp/sign-android-release@v2
        id: sign_apk
        with:
          releaseDir: app/build/outputs/apk/release
          signingKey: ${{ secrets.ANDROID_SIGNING_KEY }} # see https://github.com/ilharp/sign-android-release
          keyAlias: ${{ secrets.ANDROID_KEY_ALIAS }}
          keyStorePassword: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.ANDROID_KEY_PASSWORD }}
          buildToolsVersion: 36.0.0

      - name: Fix APK name # signing tool does funky things
        run: |
          mkdir release
          cp ${{ steps.sign_apk.outputs.signedFile }} release/app-release.apk

      - name: Upload mobile artifact
        uses: actions/upload-artifact@v4
        with:
          path: release/app-release.apk
          name: app-release-apk

  release:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download APK artifacts
        uses: actions/download-artifact@v4
        with:
          name: app-release-apk
          path: artifacts/

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: artifacts/app-release.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
